name: VeganSis
favicon: null
layout_spectrum: 0.33953761449083686
typography_spectrum: 0.43504
title: VeganSis - two sisters - one lifestyle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-36651470-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#808080'
    - '#ffffff'
    - '#00ffff'
    - '#ff0000'
  brandStrength: 0.18837586999870837
  lightness: 0.5055346658919007
  saturation: 0.6438121707178652
  rhythmicContrast: 0.831952593754977
purpose: []
